---

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.prospectors:
- type: log
  paths:
    - /var/log/example/*.log
  encoding: plain
  include_lines: ['^\{']
  processors:
  - decode_json_fields:
      when.regexp:
        message: '^{'
      fields: message
      target: ""
  - drop_fields:
      when.regexp:
        message: '^{'
      fields: message

output.kafka:
  hosts: ["kafka:9092"]
  topic: logs
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000